name: Build Executable

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
    - name: Build executable with PyInstaller
      run: |
        pip install pyinstaller
        pyinstaller --onefile --add-data "src/PDF_tree.py;." src/pdf_extractor.py
    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: my-python-app-executable
        path: dist/pdf_extractor.exe